image: node:14

build:
  stage: build
  script:
  - npm install
  - npm run build production "HTML tag with text content includes special characters - < '  - auto build"
  artifacts:
    paths:
      - dist
    expire_in: 10 min