image: node:14

build:
  stage: build
  script:
  - npm install
  - npm run build production "Fix toString Object - FunctionScript - auto build"
  artifacts:
    paths:
      - dist
    expire_in: 10 min