image: node:14

build:
  stage: build
  script:
  - npm install
  - npm run build production "Request packages on production - require-on-start - auto build"
  artifacts:
    paths:
      - dist
    expire_in: 10 min