name: Release
on:
  push:
    branches:
      - master
concurrency: release-${{ github.ref }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install modules
        run: npm ci --ignore-scripts && npm install -g wasm-pack
      - name: Build
        run: npm run build production && npm run postinstall
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
